- name: install required Packages
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
    - ftp
    - vsftpd
    
- name: Configure firewall to allow FTP service
  firewalld:
    service: ftp
    port: 20-21/tcp
    permanent: true
    state: enabled
  notify: restart firewalld

- name: Configure selinux booleans
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  with_items:
    - ftp_home_dir
    - ftpd_full_access
  ignore_errors: yes
    
- name: Configure vsftpd
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd/vsftpd.conf
    mode: 0755
    backup: yes
    
- name: create the groups
  group:
    name: "{{ item }}"
  with_items:
    - "{{ vsftpd_groups }}"
  when: vsftpd_groups is defined

- name: create ftp users
  user:
    name: "{{ item.username }}"
    comment: "{{ item.name | default(omit) }}"
    groups: "{{ item.groups|join(',') if item.groups is defined }}"
    password: "{{ item.password | default(omit) }}"
    createhome: "{{ item.home_create | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
  with_items: "{{ vsftpd_users }}"
  when: vsftpd_users is defined
  
- name: define ftp shares
  file:
    state: directory
    path: "{{ vsftpd_shares_root }}/{{ item.name }}"
    owner: root
    group: "{{ item.group| default('users') }}"
    mode: "{{ item.directory_mode|default('0755') }}"
  with_items: "{{ vsftpd_shares }}"
  when: vsftpd_shares is defined

- name: restart the vsftpd service
  service:
    name: vsftpd
    state: restarted
    enabled: yes
